import { useState } from 'react';
import { ChevronDown, Plus } from 'lucide-react';
import type { Habit, HabitInput, Reward, RewardInput, Settings } from '../shared/model';
import { defaultRule, templates } from '../shared/model';
import { days, Modal, Symbol } from './ui';

export function HabitForm({ habit, initial, settings, busy, onSave, onClose }: { habit?: Habit; initial?: HabitInput; settings: Settings; busy: boolean; onSave: (input: HabitInput) => Promise<boolean>; onClose: () => void }) {
  const [form, setForm] = useState<HabitInput>(habit ? { name: habit.name, category: habit.category, icon: habit.icon, color: habit.color, rule: habit.versions.at(-1)!.rule } : initial ?? { name: '', category: 'Personal', icon: 'leaf', color: 'purple', rule: { ...defaultRule } });
  function field<K extends keyof HabitInput>(key: K, value: HabitInput[K]) { setForm(old => ({ ...old, [key]: value })); }
  function rule<K extends keyof HabitInput['rule']>(key: K, value: HabitInput['rule'][K]) { setForm(old => ({ ...old, rule: { ...old.rule, [key]: value } })); }
  return <Modal title={habit ? 'Make it work for you' : 'Plant a new habit'} onClose={onClose} wide>
    <form onSubmit={async e => { e.preventDefault(); if (await onSave(form)) onClose(); }}>
      {!habit && <div className="template-picker"><span>Start with a template</span><div>{templates.map(t => <button type="button" className="template-chip" key={t.icon} onClick={() => setForm(structuredClone(t))}><Symbol name={t.icon} size={16} />{t.category}</button>)}</div></div>}
      <label>Habit name<input required autoFocus maxLength={70} placeholder="e.g. Read a little every day" value={form.name} onChange={e => field('name', e.target.value)} /></label>
      <div className="form-row"><label>Category<input required list="categories" maxLength={30} value={form.category} onChange={e => field('category', e.target.value)} /><datalist id="categories">{['Personal','Health','Learning','Fitness','Mindfulness','Creative','Work'].map(c => <option key={c} value={c} />)}</datalist></label><label>Track progress as<select value={form.rule.type} onChange={e => { const type = e.target.value as HabitInput['rule']['type']; setForm(old => ({ ...old, rule: { ...old.rule, type, target: type === 'check' ? 1 : type === 'duration' ? 20 : 8, unit: type === 'duration' ? 'minutes' : 'times' } })); }}><option value="check">A simple checkmark</option><option value="count">A count</option><option value="duration">Time in minutes</option></select></label></div>
      {form.rule.type !== 'check' && <div className="form-row"><label>Target per day<input required type="number" min={1} max={10000} value={form.rule.target} onChange={e => rule('target', Number(e.target.value))} /></label><label>Unit<input required maxLength={24} disabled={form.rule.type === 'duration'} value={form.rule.unit} onChange={e => rule('unit', e.target.value)} /></label></div>}
      <div className="form-row"><label>Schedule<select value={form.rule.schedule} onChange={e => rule('schedule', e.target.value as HabitInput['rule']['schedule'])}><option value="daily">Every day</option><option value="weekdays">Specific weekdays</option><option value="weekly">A weekly goal</option></select></label>{form.rule.schedule === 'weekly' && <label>Sessions per week<input required type="number" min={1} max={7} value={form.rule.weeklyTarget} onChange={e => rule('weeklyTarget', Number(e.target.value))} /></label>}</div>
      {form.rule.schedule === 'weekdays' && <fieldset className="day-picker"><legend>On these days</legend>{[1,2,3,4,5,6,0].map(day => <button type="button" key={day} aria-pressed={form.rule.days.includes(day)} onClick={() => rule('days', form.rule.days.includes(day) ? form.rule.days.filter(d => d !== day) : [...form.rule.days, day])}>{days[day]}</button>)}</fieldset>}
      {form.rule.schedule === 'weekly' && <p className="field-help">Complete your daily target on this many different days. Your streak counts successful weeks.</p>}
      <div className="appearance-row"><fieldset><legend>Icon</legend><div className="icon-picker">{['book','water','move','mind','sun','code','leaf','heart'].map(icon => <button type="button" key={icon} className={form.icon === icon ? 'selected' : ''} aria-label={`${icon} icon`} aria-pressed={form.icon === icon} onClick={() => field('icon', icon as HabitInput['icon'])}><Symbol name={icon} /></button>)}</div></fieldset><fieldset><legend>Color</legend><div className="color-picker">{(['purple','blue','orange','green','pink'] as const).map(color => <button type="button" key={color} className={`swatch ${color} ${form.color === color ? 'selected' : ''}`} aria-label={`${color} color`} aria-pressed={form.color === color} onClick={() => field('color', color)} />)}</div></fieldset></div>
      <details className="advanced"><summary>Customize earnings <ChevronDown size={16} /></summary><p className="field-help">Leave blank to use your app defaults. Earnings are saved when you complete a habit.</p><div className="form-row"><label>XP per completion<input type="number" min={0} max={100000} placeholder={`Default: ${settings.defaultXp}`} value={form.rule.xp ?? ''} onChange={e => rule('xp', e.target.value === '' ? null : Number(e.target.value))} /></label><label>Coins per completion<input type="number" min={0} max={100000} placeholder={`Default: ${settings.defaultCoins}`} value={form.rule.coins ?? ''} onChange={e => rule('coins', e.target.value === '' ? null : Number(e.target.value))} /></label></div></details>
      {habit && <p className="notice">Name and appearance update now. Target, schedule, and earnings changes start tomorrow, or next week for weekly habits.</p>}
      <div className="modal-footer"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy || (form.rule.schedule === 'weekdays' && !form.rule.days.length)}>{!habit && <Plus size={17} />}{busy ? 'Saving…' : habit ? 'Save changes' : 'Create habit'}</button></div>
    </form>
  </Modal>;
}

export function RewardForm({ reward, busy, onSave, onClose }: { reward?: Reward; busy: boolean; onSave: (input: RewardInput) => Promise<boolean>; onClose: () => void }) {
  const [form, setForm] = useState<RewardInput>(reward ?? { name: '', description: '', cost: 50, icon: 'coffee', limit: 'none' });
  function field<K extends keyof RewardInput>(key: K, value: RewardInput[K]) { setForm(old => ({ ...old, [key]: value })); }
  return <Modal title={reward ? 'Edit your reward' : 'Something to look forward to'} onClose={onClose}><form onSubmit={async e => { e.preventDefault(); if (await onSave(form)) onClose(); }}>
    <label>Reward name<input required autoFocus maxLength={70} placeholder="e.g. A coffee at my favorite place" value={form.name} onChange={e => field('name', e.target.value)} /></label>
    <label>A little description<textarea maxLength={140} placeholder="Make it something that feels good." value={form.description} onChange={e => field('description', e.target.value)} /></label>
    <div className="form-row"><label>Coin cost<input required type="number" min={1} max={100000} value={form.cost} onChange={e => field('cost', Number(e.target.value))} /></label><label>Redemption limit<select value={form.limit} onChange={e => field('limit', e.target.value as RewardInput['limit'])}><option value="none">No limit</option><option value="daily">Once per day</option><option value="weekly">Once per week</option></select></label></div>
    <fieldset><legend>Pick an icon</legend><div className="icon-picker">{['coffee','film','gift','game','food','trip'].map(icon => <button type="button" key={icon} className={form.icon === icon ? 'selected' : ''} aria-label={`${icon} icon`} aria-pressed={form.icon === icon} onClick={() => field('icon', icon as RewardInput['icon'])}><Symbol name={icon} /></button>)}</div></fieldset>
    <div className="modal-footer"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy}>{busy ? 'Saving…' : reward ? 'Save changes' : 'Create reward'}</button></div>
  </form></Modal>;
}
