import { useRef, useState } from 'react';
import { Archive, ArrowDownToLine, ArrowUpFromLine, CalendarDays, Check, ChevronLeft, ChevronRight, Flame, Gift, MessageSquare, Pencil, Plus, RotateCcw, Save, ShieldCheck, Sparkles, Sprout, Zap } from 'lucide-react';
import type { Reward, Settings, State } from '../shared/model';
import { addDays, balances, isScheduled, rewardAvailable, ruleAt, streak, weekOf, weekday } from '../shared/model';
import type { RunCommand } from './App';
import { Coin, dateLabel, Empty, Modal, Symbol } from './ui';
import { NoteForm } from './NoteForm';
import { WeeklyReview } from './WeeklyReview';

export function ProgressScreen({ state, today, busy, run, openDay }: { state: State; today: string; busy: boolean; run: RunCommand; openDay: (day: string) => void }) {
  const [month, setMonth] = useState(today.slice(0, 7));
  const [selected, setSelected] = useState<string | null>(null);
  const [habitId, setHabitId] = useState('all');
  const [confirmEntry, setConfirmEntry] = useState<string | null>(null);
  const [noteId, setNoteId] = useState<string | null>(null);
  const [notesOnly, setNotesOnly] = useState(false);
  const noteEntry = state.entries.find(entry => entry.id === noteId);
  const entries = state.entries.filter(e => habitId === 'all' || e.habitId === habitId);
  const complete = entries.filter(e => e.complete);
  const start = month + '-01';
  const nextMonth = addDays(start, 32).slice(0, 7) + '-01';
  const monthDays = Number(addDays(nextMonth, -1).slice(-2));
  const offset = (weekday(start) - state.settings.weekStart + 7) % 7;
  const balance = balances(state);
  const best = Math.max(0, ...state.habits.filter(h => habitId === 'all' || h.id === habitId).map(h => streak(state, h, today)));
  const history = [...entries].filter(e => !notesOnly || !!e.note).filter(e => selected ? e.date === selected : e.date.startsWith(month)).sort((a,b) => b.date.localeCompare(a.date));
  const rolling = Array.from({ length: 7 }, (_, i) => addDays(today, i - 6));
  const earnedWeek = state.entries.filter(e => e.date >= rolling[0] && e.date <= today).reduce((sum, e) => sum + e.xp, 0);
  const weeks = Array.from({ length: 8 }, (_, i) => addDays(weekOf(today, state.settings.weekStart), (i - 7) * 7));
  const maxWeekly = Math.max(1, ...weeks.map(w => complete.filter(e => e.date >= w && e.date < addDays(w, 7)).length));
  const pending = state.entries.find(e => e.id === confirmEntry);
  return <>
    <div className="page-heading"><div><p className="date-heading">Every check-in tells a story</p><h1>Look how far you’ve come.</h1><p>Find your rhythm, celebrate your effort, and keep growing.</p></div><select className="habit-filter" aria-label="Filter progress by habit" value={habitId} onChange={e => setHabitId(e.target.value)}><option value="all">All habits</option>{state.habits.map(h => <option key={h.id} value={h.id}>{h.name}{h.archived ? ' (archived)' : ''}</option>)}</select></div>
    <div className="stats-grid"><div className="stat-card"><span className="stat-icon green"><Check size={22} /></span><strong>{complete.length}</strong><span>Total completions</span></div>{state.settings.showStreaks && <div className="stat-card"><span className="stat-icon orange"><Flame size={22} /></span><strong>{best}</strong><span>Best current streak*</span></div>}{state.settings.showXp && <><div className="stat-card"><span className="stat-icon purple"><Zap size={22} /></span><strong>{balance.xp}</strong><span>Lifetime XP · all habits</span></div><div className="stat-card"><span className="stat-icon blue"><Sparkles size={22} /></span><strong>{earnedWeek}</strong><span>XP in the last 7 days · all habits</span></div></>}</div>
    <WeeklyReview state={state} today={today} habitId={habitId} />
    <div className="progress-layout"><section className="panel calendar-panel"><div className="section-heading"><h2>Your consistency</h2><div className="date-nav"><button className="icon-button" aria-label="Previous month" onClick={() => { setMonth(addDays(start, -1).slice(0,7)); setSelected(null); }}><ChevronLeft size={18} /></button><strong>{dateLabel(start, { month: 'long', year: 'numeric' })}</strong><button className="icon-button" aria-label="Next month" disabled={month >= today.slice(0,7)} onClick={() => { setMonth(nextMonth.slice(0,7)); setSelected(null); }}><ChevronRight size={18} /></button></div></div><div className="calendar-weekdays">{Array.from({length:7},(_,i)=>(i+state.settings.weekStart)%7).map(d => <span key={d}>{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][d]}</span>)}</div><div className="calendar-grid">{Array.from({length:offset},(_,i)=><span key={`space-${i}`} />)}{Array.from({length:monthDays},(_,i)=>addDays(start,i)).map(day => {
      const done = complete.filter(e => e.date === day).length;
      const resting = entries.some(e => e.date === day && e.rested);
      const planned = state.habits.filter(h => (habitId === 'all' || h.id === habitId) && isScheduled(h,day) && ruleAt(h,day).schedule !== 'weekly').length;
      const intensity = done ? done >= Math.max(1, planned) ? 'full' : 'some' : resting ? 'resting' : '';
      return <button key={day} className={`calendar-day ${intensity} ${day === today ? 'today' : ''} ${selected === day ? 'selected' : ''}`} disabled={day > today} aria-label={`${dateLabel(day, {month:'long',day:'numeric'})}, ${done} completed${resting ? ', rest day' : ''}`} aria-pressed={selected === day} onClick={()=>setSelected(selected === day ? null : day)}><span>{iDay(day)}</span><small>{done ? <Check size={12}/> : resting ? <Sprout size={12}/> : null}</small></button>;
    })}</div><div className="calendar-legend"><span>Less</span><i/><i className="some"/><i className="full"/><span>More progress</span><button className="text-button" onClick={()=>setSelected(null)}>Show whole month</button></div></section>
    <section className="panel weekly-panel"><h2>Growing, week by week</h2><p>Completions over the last 8 weeks</p><div className="bar-chart" role="img" aria-label={weeks.map(w=>`${dateLabel(w)}: ${complete.filter(e=>e.date>=w&&e.date<addDays(w,7)).length} completions`).join('; ')}>{weeks.map(w=>{ const count=complete.filter(e=>e.date>=w&&e.date<addDays(w,7)).length; return <div className="bar-column" key={w}><span>{count}</span><div className="bar-space"><i style={{height:`${Math.max(3,count/maxWeekly*100)}%`}} /></div><small>{dateLabel(w)}</small></div>; })}</div><p className="chart-note">Consistency looks different every week. All progress counts.</p></section></div>
    <section className="panel history-panel"><div className="section-heading"><h2>{selected ? dateLabel(selected,{month:'long',day:'numeric'}) : 'Check-in history'}</h2><div className="history-controls">{selected && <button className="text-button" onClick={() => openDay(selected)}><CalendarDays size={15} />Open this day</button>}<a className="text-button" href="/api/export/csv" download="streakify-check-ins.csv" title="Export all check-ins, including notes"><ArrowDownToLine size={15} />Export CSV</a><button className="text-button" aria-pressed={notesOnly} onClick={() => setNotesOnly(!notesOnly)}><MessageSquare size={15} />{notesOnly ? 'Show all check-ins' : 'With notes only'}</button><span className="muted">{history.length} entries</span></div></div>{!history.length ? <Empty icon="book" title="Your story is just getting started" text="Your check-ins and rest days will appear here. Start with one small step on Today." /> : <div className="history-list">{history.map(entry=>{ const habit=state.habits.find(h=>h.id===entry.habitId)!; return <div className="history-row" key={entry.id}><span className={`habit-icon small ${habit.color}`}><Symbol name={habit.icon} size={19}/></span><div><strong>{habit.name}</strong><small>{dateLabel(entry.date)} · {entry.rested ? 'Rest day' : entry.complete ? 'Completed' : `${entry.value} / ${entry.rule.target} ${entry.rule.unit}`}</small>{entry.note && <p className="history-note">{entry.note}</p>}</div><button className="icon-button" aria-label={`Edit note for ${habit.name} on ${entry.date}`} onClick={() => setNoteId(entry.id)}><MessageSquare size={17} /></button><span className="history-earnings">{state.settings.showXp && `+${entry.xp} XP`}{state.settings.showCoins && <small><Coin size={13}/>{entry.coins}</small>}</span><button className="icon-button" aria-label={`Undo ${habit.name} on ${entry.date}`} disabled={busy} onClick={()=>setConfirmEntry(entry.id)}><RotateCcw size={17}/></button></div>; })}</div>}</section>
    {state.settings.showStreaks && <p className="page-footnote">*Streaks count scheduled days, or successful weeks for weekly habits.</p>}
    {noteEntry && <NoteForm entry={noteEntry} habitName={state.habits.find(h => h.id === noteEntry.habitId)!.name} busy={busy} run={run} onClose={() => setNoteId(null)} />}
    {pending && <Modal title="Undo this check-in?" onClose={()=>setConfirmEntry(null)}><p className="confirm-copy">This removes the saved progress and reverses its {pending.xp} XP and {pending.coins} coins. You can log it again from Today.</p><div className="modal-footer"><button className="button secondary" onClick={()=>setConfirmEntry(null)}>Cancel</button><button className="button primary" disabled={busy} onClick={async()=>{ if(await run({type:'entry.set',habitId:pending.habitId,date:pending.date,value:0},'Check-in undone. Earnings reversed.')) setConfirmEntry(null); }}>Undo check-in</button></div></Modal>}
  </>;
}
function iDay(date:string) { return Number(date.slice(-2)); }

export { RewardsScreen } from './RewardsScreen';

export function SettingsScreen({state,busy,run,restore,notify}:{state:State;busy:boolean;run:RunCommand;restore:(state:State)=>void;notify:(message:string)=>void}) {
  const [form,setForm]=useState<Settings>(state.settings);
  const [backup,setBackup]=useState<{name:string;data:unknown}|null>(null);
  const [restoring,setRestoring]=useState(false);
  const fileRef=useRef<HTMLInputElement>(null);
  function field<K extends keyof Settings>(key:K,value:Settings[K]) {setForm(old=>({...old,[key]:value}));}
  const toggles=[{key:'showXp',label:'XP & levels',description:'See your effort grow into new milestones.',icon:Zap},{key:'showCoins',label:'Coin indicators',description:'Show coin earnings and your wallet balance.',icon:Gift},{key:'showStreaks',label:'Streaks',description:'Celebrate consistency on your schedule.',icon:Flame}] as const;
  async function importBackup() {
    setRestoring(true);
    try {const response=await fetch('/api/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(backup?.data)});const result=await response.json();if(!response.ok)throw new Error(result.error);restore(result);setForm(result.settings);setBackup(null);}catch(error){notify(error instanceof Error?error.message:'Backup could not be restored.');}finally{setRestoring(false);}
  }
  return <><div className="page-heading"><div><p className="date-heading">A space that feels like you</p><h1>Your habits. Your way.</h1><p>Start with good defaults, then make them your own.</p></div></div><form className="settings-layout" onSubmit={async e=>{e.preventDefault();await run({type:'settings.save',settings:form},'Settings saved. Make yourself at home.');}}>
    <div className="settings-main"><section className="panel settings-panel"><div className="settings-heading"><span className="stat-icon purple"><Symbol name="sun" size={21}/></span><div><h2>Your personal space</h2><p>A few details to make your days feel right.</p></div></div><div className="form-row"><label>Your name<input required maxLength={40} value={form.name} onChange={e=>field('name',e.target.value)}/></label><label>Appearance<select value={form.theme} onChange={e=>field('theme',e.target.value as Settings['theme'])}><option value="light">Light</option><option value="dark">Dark</option><option value="system">Match my device</option></select></label></div><div className="form-row"><label>Timezone<input required list="timezones" value={form.timezone} onChange={e=>field('timezone',e.target.value)}/><datalist id="timezones">{Intl.supportedValuesOf('timeZone').map(t=><option key={t} value={t}/>)}</datalist></label><label>Week starts on<select disabled={state.entries.length>0} value={form.weekStart} onChange={e=>field('weekStart',Number(e.target.value) as 0|1)}><option value={1}>Monday</option><option value={0}>Sunday</option></select></label></div><button className="text-button" type="button" onClick={()=>field('timezone',Intl.DateTimeFormat().resolvedOptions().timeZone)}>Use my device’s timezone</button><p className="field-help">Check-ins keep their original dates when you change timezone. Week start is fixed after your first check-in to preserve weekly history.</p></section>
    <section className="panel settings-panel"><div className="settings-heading"><span className="stat-icon orange"><Zap size={21}/></span><div><h2>Set the pace</h2><p>Default earnings for habits without a custom override.</p></div></div><div className="form-row"><label>XP per completion<input type="number" required min={0} max={100000} value={form.defaultXp} onChange={e=>field('defaultXp',Number(e.target.value))}/></label><label>Coins per completion<input type="number" required min={0} max={100000} value={form.defaultCoins} onChange={e=>field('defaultCoins',Number(e.target.value))}/></label></div><div className="form-row"><label>XP per level<input type="number" required min={10} max={100000} value={form.levelSize} onChange={e=>field('levelSize',Number(e.target.value))}/></label><label>Streak XP bonus (%)<input type="number" required min={0} max={100} value={form.streakBonus} onChange={e=>field('streakBonus',Number(e.target.value))}/></label></div><p className="field-help">Earnings changes apply to future completions. The optional bonus adds a percentage when a habit already has a streak. Changing XP per level recalculates your level from lifetime XP.</p></section>
    <section className="panel settings-panel"><div className="settings-heading"><span className="stat-icon green"><Sparkles size={21}/></span><div><h2>Choose your motivation</h2><p>Keep the parts that help you show up.</p></div></div>{toggles.map(t=><label className="toggle-row" key={t.key}><span className="toggle-copy"><t.icon size={19}/><span><strong>{t.label}</strong><small>{t.description}</small></span></span><input type="checkbox" className="switch-input" checked={form[t.key]} onChange={e=>field(t.key,e.target.checked)}/><span className="switch-track" aria-hidden="true"/></label>)}<p className="field-help">These switches hide progress indicators. Earnings and history are preserved. Set default earnings to zero if you want to stop earning points.</p></section>
    <div className="settings-save"><button className="button primary" disabled={busy}><Save size={17}/>{busy?'Saving…':'Save settings'}</button></div></div>
    <aside><section className="panel backup-panel"><span className="stat-icon blue"><ShieldCheck size={22}/></span><h2>Keep your progress safe</h2><p>Export your habits, history, and rewards as a backup you can restore anytime.</p><a className="button secondary" href="/api/export" download="streakify-backup.json"><ArrowDownToLine size={17}/>Export backup</a><button className="button ghost" type="button" onClick={()=>fileRef.current?.click()}><ArrowUpFromLine size={17}/>Restore a backup</button><input hidden type="file" ref={fileRef} accept="application/json,.json" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>4*1024*1024){notify('Choose a backup smaller than 4 MB.');return;}try{setBackup({name:file.name,data:JSON.parse(await file.text())});}catch{notify('This file is not valid JSON. Choose a Streakify backup.');}}}/><small>Restoring replaces the current workspace. Export a copy first if you want to keep it.</small></section><div className="settings-note"><Sprout size={21}/><p>The best system is the one you’ll actually use. You can change these settings as you grow.</p></div></aside>
    </form>{backup&&<Modal title="Restore this backup?" onClose={()=>!restoring&&setBackup(null)}><p className="confirm-copy">“{backup.name}” will replace your current habits, history, rewards, and settings. Invalid backups are rejected without changing your data.</p><div className="modal-footer"><button className="button secondary" disabled={restoring} onClick={()=>setBackup(null)}>Cancel</button><button className="button primary" disabled={restoring} onClick={()=>void importBackup()}>{restoring?'Restoring…':'Replace and restore'}</button></div></Modal>}</>;
}
